### ISSUE TITLE
a way to manage large bodies

### ISSUE THREAD

**Issue by nephatrine** [Entity378/LC-SellBodiesFixed#2]
While you did fix the bodies that were really problematic to carry around like the bracken, the other problem with large bodies is just that if you've got a few dead dogs on the ship it makes it very difficult to find and pick up things. They're just too huge. Would be nice to have an option to make some of the drops physically smaller just for storage purposes (same weight and whatnot though). That or a specific rack for dead bodies or way to compress them or something.

**Comment by Entity378** [comment]
due to how the mod is made I don't know if it is possible to implement the ability to change the size of the bodies. What I can do is change the model of the body with one of its "components", in the case of the dog I could make one of its teeth fall out, instead of the entire body. However, I'm currently taking a break and I don't know when I'll release a new update

**Comment by Entity378** [comment]
I changed the body of the Eyeless Dog with its teeth (the drop is now significantly smaller)
