### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by superstrongbozo** [Entity378/LC-SellBodiesFixed#3]
ho do i kill jester, coil head, rad mech, spore lizard,hydrodere and ghost girl if they are invincible?

**Comment by Entity378** [comment]
I simply added support for those bodies in case other mods made those enemies killable. My mod itself doesn't allow you to kill non-killable enemies in the vanilla game. To kill those enemies you could use EverythingCanDie by disabling the explosions config (otherwise it won't work). I cannot assure you that the solution I proposed will work 100%.

**Comment by superstrongbozo** [comment]
@Entity378 they are still just despawning

**Comment by Entity378** [comment]
I know that the EverythingCanDie dev is (quietly) fixing the mod so be patient while he finishes updating it. Otherwise try some other mod.
